### ISSUE TITLE
Suggestion - Record ID's of grabbed videos in a text file

### ISSUE THREAD

**Issue by simonk83** [harryr0se/giant_bomb_cli#3]
Hi, no idea if you still care about this, but I've been using it a bit and would love to automate things a little.

I've been playing with youtube-dl (https://github.com/rg3/youtube-dl/blob/master/README.md#readme) which has a very handy option:

```
--download-archive FILE          Download only videos not listed in the
                                 archive file. Record the IDs of all
                                 downloaded videos in it.
```

This easily allows you to set up the script to run daily (or whatever) to download new videos, and it'll check that text file and skip any video ID you've already grabbed.  I'd love to do this for Giant Bomb video series that they might release sporadically.  

Thanks!

**Comment by harryr0se** [comment]
Thanks for the suggestion, still happy to make updates to the script. This sounds like a good feature! 
I'll look into implementing it shortly :)

**Comment by harryr0se** [comment]
Hey Simon :)

I've added a first pass of the `--download-archive` argument

All that's required is that you pass a consistent path to the script each run and it will keep the archive updated.
Example:
```
giant_bomb_cli.py --filter --video_show 28 --download --download-archive path/to/archive 
```

Let me know if that works for you!

**Comment by simonk83** [comment]
Thanks Harry, that's awesome!  Just tested it now and it works great, but it has created another issue that I didn't consider.  If I'm going to set and forget this to download recurring series videos, it'd be really good to be able to pass multiple show ID's in there, otherwise it'd require another copy of the script per video series.  

Not sure what's easier there, a comma separated list in the script itself (eg giant_bomb_cli.py --filter --video_show 28,30,39 --download) or maybe another text file with a list of all the ID's to search for?  Probably the former to be honest but you'd know better than me :)

Does that all make sense?

**Comment by simonk83** [comment]
Oh oh, thought of something else, sorry! 😄. With all the above, say the script fails to find anything for the first item, would it be possible to have it skip that and move on to the next in the list until its checked all items?

**Comment by harryr0se** [comment]
Heya, really sorry for the delay in this response!

>  If I'm going to set and forget this to download recurring series videos, it'd be really good to be able to pass multiple show ID's in there, otherwise it'd require another copy of the script per video series.

It doesn't seem like the api supports searching through multiple shows at once (happy to be corrected!). Unfortunately at the moment I don't have time to implement this feature, what I can suggest is using a wrapper script which makes multiple calls to ```giant_bomb_cli```?

So you'd have a bash script that ran.
```text
giant_bomb_cli.py --filter --video_show 28 --download --download-archive path/to/archive
giant_bomb_cli.py --filter --video_show 3 --download --download-archive path/to/archive 
```

Hopefully that should achieve the same thing :)
