### ISSUE TITLE
I think something must have changed with the recent site redesign

### ISSUE THREAD

**Issue by simonk83** [harryr0se/giant_bomb_cli#4]
Having issues downloading files now, most things (single files and also specific video_shows) aren't found.

For example they just added a Hitman 2 quick look, which seems to be titled "Quick Look: Hitman 2 (Quick Looks)"

Normally, just searching for "quick look: hitman 2" would find this, but even putting the entire word for word title in there doesn't find it.   Only searching for Hitman 2 eventually brings it up, but along with a lot of other crap of course :)

Could just be teething issues at their end but thought I'd best report it anyway just in case.

Thanks!

**Comment by harryr0se** [comment]
Hey Simon!

I'm seeing that ```giant_bomb_cli.py --filter --name "Quick Look: Hitman 2"``` doesn't pick anything up which is odd, not sure the reasoning though. I suspect it's an issue on their end as the video isn't picked up [when searching on the site either.](https://www.giantbomb.com/search/?header=1&q=quick%20look%3A%20hitman%202)

Filtering by the game name and then using the ```video_show``` filter does work for this case though :) ( 3 = quick looks )
```giant_bomb_cli.py --filter --name "Hitman 2" --video_show 3```

Downloads seem to be working fine for me, perhaps it was a temporary thing during their big update? Can you confirm if you're still having issues?

**Comment by simonk83** [comment]
Hey :)
Yep downloads are working fine, it's just certain stuff not able to be found, so you're right it must be at their end (which I suppose isn't too surprising given the changes).
